openapi: 3.1.0
info:
  title: poc-documentation
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/domains/{domainId}':
    parameters:
      - schema:
          type: string
        name: domainId
        in: path
        required: true
    get:
      summary: Retrieve a domain
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      parameters:
        - schema:
            type: string
          in: cookie
    patch:
      summary: Update a domain
      operationId: patch-domains-domainId
      responses:
        '200':
          description: OK
    delete:
      summary: Delete a domain
      operationId: delete-domains-domainId
      responses:
        '200':
          description: OK
  /domains:
    get:
      summary: Retrieve domains
      tags: []
      responses: {}
      operationId: get-domains
components:
  schemas:
    Domain:
      title: Domain
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        name:
          type: string
        levels:
          type: array
          items:
            type: string
        users:
          type: array
          items:
            type: string
        '':
          type: string
      required:
        - id
